[package]
name = "asciidoc-parser"
version = "0.1.0"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2021"
authors = ["Eric Scouten <git@scouten.me>"]
keywords = ["asciidoc", "parser"]
repository = "https://github.com/scouten/asciidoc-parser"
rust-version = "1.72.0"

[dependencies]
