= Notices for the AsciiDoc Language Project

This content is produced and maintained by the AsciiDoc Language project.

Project home: https://projects.eclipse.org/projects/technology.asciidoc

== Trademarks

AsciiDoc and AsciiDoc Language are trademarks of the Eclipse Foundation.
Eclipse and the Eclipse Logo are registered trademarks of the Eclipse Foundation.

== Copyright

All content is the property of the respective authors or their employers.
For more information regarding authorship of content, please consult the listed source code repository logs.

== Declared Project Licenses

This technology specification and its accompanying materials are made available under the terms of the Eclipse Public License v 2.0, which is available at https://www.eclipse.org/legal/epl-2.0/.

SPDX-License-Identifier: EPL-2.0

The end user documentation content for the AsciiDoc Language is made available under the terms of a Creative Commons Attribution 4.0 International License, which is available at https://creativecommons.org/licenses/by/4.0/.

SPDX-License-Identifier: CC-BY-4.0

== Source Code

The project maintains the following source code repositories:

* https://gitlab.eclipse.org/eclipse/asciidoc/asciidoc-lang

////
== Third-party Content

library/project/product name (version)

* License:
* Project: <project url> (optional)
* Source: <download/source-url> (optional)
////

== Cryptography

Content may contain encryption software.
The country in which you are currently may have restrictions on the import, possession, and use, and/or re-export to another country, of encryption software.
BEFORE using any encryption software, please check the country's laws, regulations and policies concerning the import, possession, or use, and re-export of encryption software, to see if this is permitted.
