= AsciiDoc Language Project

This project maintains the AsciiDoc Language Specification, Technology Compatibility Kit (TCK), end user documentation, and their related materials.
The AsciiDoc Language Specification describes the syntax and grammar, Abstract Semantic Graph (ASG), Document Object Model (DOM), referencing system, and APIs for processing, converting, and extending the language.
The TCK is used to verify and certify that an AsciiDoc processor implementation is compatible with this specification.
For further details, see the xref:process/scope.adoc[project's approved scope].

== Build the End User Documentation

This repository is a registered content source in the https://github.com/asciidoctor/docs.asciidoctor.org/blob/main/antora-playbook.yml[playbook file for docs.asciidoctor.org].
The source files under the [.path]_docs/_ folder are organized into a documentation component as identified by the [.path]_antora.yml_ file.

To build and preview the documentation locally, follow the instructions in the file link:local-antora-playbook.yml[] at the root of this repository.
To learn more about how to build a documentation site with Antora, see the https://docs.antora.org/antora/latest/install-and-run-quickstart/[Install and Run Antora Quickstart].

== Licenses

The AsciiDoc Language and the accompanying materials are made available under the terms of the Eclipse Public License v 2.0 (EPL-2.0).
See link:LICENSE[] to find the full license text.

The end user documentation for the AsciiDoc Language, located in the [.path]_docs/_ folder, is made available under the terms of a https://creativecommons.org/licenses/by/4.0/[Creative Commons Attribution 4.0 International License] (CC-BY-4.0).

See xref:NOTICE.adoc[NOTICE] for additional license and copyright information.

== Trademarks

AsciiDoc(R) and AsciiDoc Language(TM) are trademarks of the Eclipse Foundation, Inc.
