= SDR-4: Use PEG as the Formal Grammar for Describing the AsciiDoc Language

[horizontal]
Related issues::
* https://gitlab.eclipse.org/eclipse/asciidoc-lang/asciidoc-lang/-/issues/8[asciidoc-lang#8]

== Context

The backbone of a specification for a formal language, such as AsciiDoc, is a formal grammar.
A formal grammar describes the syntax of a language in terms of what combinations of strings are valid, as well as any semantics associated with those combinations.
The grammar consists of a set of rules that describe the markup elements, their relationships, and required ordering and precedence.
The grammar is complemented by a parser, which transforms the input matched by a rule into a node and articulates the semantic rules.
A formal grammar for AsciiDoc moves the details of parsing away from implementation-specific code into something other implementations can reference and build on.

We need to choose what grammar formalism to use to describe the syntax of the AsciiDoc language in the specification.
That formalism also needs to be able to express any required semantics associated with those rules in the form of rule actions.
In other words, we must choose a solution that provides fully semantic parsing, with the goal of producing an ASG, not just lexical parsing.

== Accepted decision

We've decided to use a parsing expression grammar (PEG) as the formal grammar in the specification to describe the AsciiDoc language.
In particular, we've chosen the https://peggyjs.org/documentation.html#grammar-syntax-and-semantics-parsing-expression-types[Peggy dialect] of PEG.
Peggy provides the full expression of a PEG parser.
During prototyping, its dialect has proven to be flexible, concise, and readable.

The normative sections of the specification will use a PEG grammar and rule actions as a way to communicate the syntax rules, relationships, and expected behaviors of the AsciiDoc language.

Please note that it's not necessary for an implementation to use a PEG parser, or even to reuse the grammars and its rules provided by the specification.
To cite https://blog.reverberate.org/2013/09/ll-and-lr-in-context-why-parsing-tools.html:

> Language specifications are often defined in terms of a formalism like BNF, but it’s almost never the case that real parsers can be generated directly from this formalism.

All that matters is whether the implementation produces the expected ASG.
However, we feel strongly that the grammars in the specification will clearly communicate the valid syntax rules and required semantics for parsing the AsciiDoc language, and will provide a good starting point for writing an implementation.

== Decision summary

We must keep in mind that we're writing a specification, and hence formal grammar, for an existing language.
The implementation-defined history of AsciiDoc leading up to the specification effort has resulted in some aspects of the language being tightly coupled with how it's parsed.
A goal of the specification is to untangle the syntax so it can be clearly described in the specification.

Since the language was established before any attempt to formalize it, the grammar will necessarily have to adapt to its inherent rules rather than the other way around.
That severely limits which grammar formalisms are applicable for describing the AsciiDoc language.
AsciiDoc is often context sensitive, as opposed to context free as many grammar formalisms require.
AsciiDoc is also naturally recursive, yet often relies on semantic boundaries.
Thus, many existing grammar formalisms may not apply well to the AsciiDoc language.

We've discovered that PEG is the most well-suited formalism for describing AsciiDoc using a formal grammar in the specification.
We've focused on Peggy (a JavaScript-based PEG implementation) since it has proven to be the most accommodating to the task.

=== Why PEG?

AsciiDoc is not a context-free language.
Furthermore, parsing AsciiDoc cannot be ambiguous, meaning there's only one valid parse tree.
That means parsing AsciiDoc relies on the ordered choice operator, which, at times, must tap into assertions and semantic predicates to make that choice.
An assertion looks ahead of the cursor to check an adjacency requirement without consuming any characters.
A predicate is an arbitrarily complex expression or action to look ahead into the input string without actually consuming it.
That already puts us squarely into the feature set of PEG.

To cite https://blog.reverberate.org/2013/09/ll-and-lr-in-context-why-parsing-tools.html:

> Parsing expression grammars avoid ambiguity by forcing all grammar rules to be defined in terms of prioritized choice.

That precisely describes the deterministic interpretation that AsciiDoc requires.

There's another characteristic of AsciiDoc that leads us to conclude that PEG is the right choice to describe AsciiDoc.
Any sequence of Unicode characters is considered a parseable AsciiDoc document, even if it emits warnings in certain cases.
That's because AsciiDoc is first and foremost a language for writing, not programming.
The language must assume that if no grammar rules match, meaning no reserved markup is found, then the text is intended to be content for the reader's eyes.
On the other hand, if a sequence of characters, such as a block delimiter line, matches a grammar rule, then that sequence of characters is interpreted to have semantic meaning, such as wrapping content in a sidebar block.
PEG also supports regex character matches, which is crucial for supporting all written languages (i.e., Unicode).

In many aspects of the language, AsciiDoc relies on recursive descent (section hierarchy, delimited blocks, nested text formatting, etc).
PEG operates as a recursive descent parser, making it a natural fit.

In PEG, actions can be associated with rules to transform the parsed result into a semantic node, which is vital for describing how an element must be interpreted.
It's not enough for us to merely document the valid syntax of AsciiDoc; we also need to document the required semantics.
Actions in PEG give us this capability without having to introduce a separate formalism.

Based on these needs, we've been able to conclude that AsciiDoc lends itself well to a PEG parser.
We rely on the power of PEG parsing to describe the AsciiDoc language, at least for the purpose of writing the specification.

We don't have to worry about the inefficiency of PEG as much since AsciiDoc's line and marker-oriented style is already naturally designed to be able to veto rules early.
In this regard, the language is quite well-suited to parsers generated by PEG.

The PEG page on wikipedia asserts that not all languages that can be expressed using parsing expression grammars can be parsed by LL or LR parsers.
We think this is the case for AsciiDoc as well, though it remains an open question to prove or disprove.

=== Multiple grammars

In order to describe AsciiDoc in a way that achieves reasonable backwards compatibility, it's not possible to use a single grammar, as first asserted in https://www.tweag.io/blog/2021-06-15-asciidoc-haskell-pandoc.
Rather, the language must be described using several different grammars listed here:

* line preprocessor (possible to integrate into block grammar if the parser supports it)
* block
* attrlist
* inline preprocessor
* inline

The primary reason to split the grammars is because blocks and inlines are parsed in fundamentally different ways.
Blocks are largely line-oriented.
Thus, every such rule has to consider a line ending as a meaningful character, often a boundary.
Inlines see line endings as just another type of spacing character and will comfortably span them.
Another reason is that the block name determines which root grammar rule to use to parse the inline syntax, if any.

Thus, due to how the language evolved, there are natural restarts between each of these stages of parsing that require shifting to a subparser.
Trying to describe the language using a single grammar would permit behavior forbidden by design, such as a paragraph running over the end of a delimited block or a block attribute value running over the end of a line.

==== Line preprocessor

There's no question that the line preprocessor is the biggest hurdle for describing AsciiDoc using a formal grammar.
That's because it's intertwined with the block structure, meaning it's both dependent on it and can influence it.
It's possible this part of the grammar can be described using a dedicated grammar, but implementations may chose to integrate it directly into the block grammar or to use a different strategy entirely. 
We're likely going to describe the line preprocessor using a dedicated PEG grammar in the specification since it will be the easiest to understand.
To integrate the line preprocessor into the block grammar relies on the PEG parser allowing the input to be modified ahead of what's already been parsed.
We're also still considering whether we can tighten the rules to decouple the line preprocessor from block parsing (https://gitlab.eclipse.org/eclipse/asciidoc-lang/asciidoc-lang/-/issues/26[#26]).

=== Assertions and semantic predicates

It's not enough to say that AsciiDoc must be described using PEG.
There are some characteristics of the language that dictate particular requirements for a grammar formalism.
AsciiDoc requires the use of the full set of features that PEG affords, most notably assertions and semantic predicates.

A good example of where assertions are required is when matching constrained inline markup.
A constrained span must not permit a space immediately after the opening mark and must not be followed by a word character.
The only way to express this requirement in a PEG is to make use of assertions.
We also see this need come up again in the block-level syntax when the rule has to avoid running over a line boundary or asserting that there's one immediately following a rule.

Expressing the block-level syntax relies heavily on semantic predicates.
For example, having to support variable length block delimiters is a good case of when semantic predicates are needed.
In AsciiDoc, a block delimiter line starts and ends a delimited block.
The parser will look for the opening delimiter, then parse input as children of that block up until the closing delimiter, not allowing the parser to consume the closing delimiter.
That part is simple enough for PEG to describe.
Except that the delimiter line can be of variable length.
Thus, to find the closing delimiter line, the grammar can't just match any delimiter line for that block type, but the delimiter line that has the same length.
When a delimiter line is matched, the grammar rule must use a semantic predicate to inspect the parsing state to determine if the delimiter line is an exact match.

A similar problem occurs with nested blocks.
It's not permissible for a block that is nested inside of another block to be closed until the parent block is closed.
Once again, the grammar rule must use a semantic predicate to determine if the rule is applicable given the current parsing context.

We see this need come up again and again in AsciiDoc, including section parsing, list parsing, and table parsing.

The block syntax in AsciiDoc is predominantly a forward-only grammar.
Once the block-level parser matches the rule that starts a block, at which point state is saved, that rule should succeed.
In other words, the parser should not have to revisit that rule.
Thus, the grammar has to be written carefully to ensure that the parsing context remains consistent.
In theory, this requirement could be avoided if we forbid the use of packrat parsing (caching).
However, it would be best if we could write the grammar in such a way that does not fail when this feature of a PEG parser is enabled.

Another place semantic predicates are needed is whenever the block attributes, specifically the block style, impacts parsing.
For example, if `[discrete]` is present above a heading, the parser should treat it as a discrete heading instead of a section/section title.
In this case, the parser needs to be able consult the block attributes to determine how to proceed.
In order to do so, the block attributes must be stored in the parsing context, making it available for the semantic predicate to consult.

To the degree possible, we will avoid relying on semantic predicates in the grammar so that it's easier to comprehend.
However, it's impossible to avoid them entirely since the language relies on them, and thus they will appear in the grammar rules in the specification.

== Backwards compatibility

Using a formal grammar to describe the AsciiDoc language, and PEG in particular, will have a few impacts on backwards compatibility.
But this impact is a positive one.
It means AsciiDoc will be parsed more accurately and deterministically.

One notable change is that nested blocks will be parsed semantically, instead of lexically.
That means that if a block is nested inside of another block, the parent block cannot be closed until the child block is closed.
This is the way almost all other recursive languages work and something writers have expected for as long as AsciiDoc has existed.
It was not possible to implement block parsing this way in pre-spec AsciiDoc since the parsing was not based on a formal grammar.
But we now have the opportunity to fix that.

Inline parsing will have a similar benefit.
When inline markup is nested, the nested markup must end before the parent markup ends.
Again, this is the behavior writers expect.
The absence of this capability has led to using defensive workarounds.
These workarounds will largely still apply, but will be rendered unnecessary.

The use of the `subs` attribute on a block is going to be more restrictive.
The grammar will be able to account for common permutations, but will not allow the grammar rules to be completely rearranged.
We're confident we'll be able to retain reasonable compatibility with existing documents while still being able to accommodate the most popular uses of this capability.

Attribute entries will become part of the block grammar.
Thus, valid locations for attribute entries will be clarified.
In some cases, this may lead to the rules being more restrictive (e.g., cannot be interspersed with block attribute lines), while in other cases it may allow the rules being more loose (e.g., can be placed at the end of a delimited block).

The changes to the syntax ushered in by a formal grammar will make the parsing of AsciiDoc more deterministic and thus be received well by writers.
We consider this change as suitable to maintain reasonable compatibility with existing documents.
