= SDR-5: Describe Inline Syntax using Formal Grammar

[horizontal]
Related issues::
* https://gitlab.eclipse.org/eclipse/asciidoc-lang/asciidoc-lang/-/issues/16[asciidoc-lang#16]
* https://gitlab.eclipse.org/eclipse/asciidoc-lang/asciidoc-lang/-/issues/16[asciidoc-lang#22]

== Context

The inline syntax in the AsciiDoc language has never had a formal grammar, nor was it initially designed to have one.
Inline syntax refers to the markup in the content of a non-verbatim leaf node (e.g., paragraph, heading, title, block content attribute, etc.).
We herein refer to this content as regular text.

The inline markup in AsciiDoc is currently processed as a sequence of substitutions on regular text using multiple passes.
These substitutions, in effect, determine how that text is interpreted.
The substitution types applied to regular text are as follows: specialchars, attributes, quotes, replacements, macros, and post_replacements.

Despite the sophistication of the regular expressions used by the substitutions to identify inline syntax, this methodology is nothing more than a battery of search and replace operations.
These operations incrementally transform the text from AsciiDoc to the output format during the convert phase.
This approach is in contrast to building a complete structured representation (i.e., parse tree) during the parsing phase.

Due to the lack of a formal grammar, the inline syntax is largely implementation-defined--or, at the very least, implementation-biased.
Furthermore, relying on substitutions to process the inline syntax has resulted in the inline syntax being the most ambiguous, fragile, and content-dependent aspect of the language.
Although we initially planned to stick with the substitutions approach in the first version of the specification, further analysis revealed that leaves severe problems unresolved:

. The source is morphing while the substitutions are being applied.
This approach makes the definition of the inline syntax ambiguous by definition since each successive substitution operates on a slightly different source, a hybrid of input and output produced by the converter.
In other words, the output actually affects the parsing.
. The processing is coupled to the converter, which is not being specified at this time.
. The parse phase is not complete before the convert phase begins, making it difficult for an implementation to produce an ASG for verification.
. The regular expression-based substitutions are complicated to describe in a technical specification.
Furthermore, due to their complexity, the regular expressions required are not portable between language runtimes, which does not meet the portability goals of the specification.

If this specification were to describe the inline syntax as a sequence of substitutions at this point, we fear these problems will cripple the specification and become so ingrained in the language that it will be impossible to correct in future versions.
Since the inline syntax shows up again and again throughout the language, this is just not an acceptable condition.
The transition away from substitutions is more pressing and consequential than we originally anticipated.
It's also worth noting that the request to formalize the inline syntax traces back over a decade.

The way the inline syntax is currently processed in AsciiDoc makes it one of the most ambiguous aspects of the language.
The specification presents a unique opportunity to address this long-standing issue.
This transition will make the inline syntax easier to understand, parse, and teach.

== Accepted decision

In order to specify the AsciiDoc language unambiguously, we've decided to make the transition from describing the inline syntax in terms of substitutions to defining it using a formal grammar--the input to a parser generator.

== Decision summary

=== Necessity

Search and replace using regular expressions leaves too many ambiguities and idiosyncrasies.
It also lacks sufficient context to account for countless permutations (e.g., constrained and nested markup, backslash escaping, etc).
As a result, the interpretation of the inline markup can often be unexpected or surprising for the writer.
We see many documents in which the writer has had to resort to workarounds or defensive markup to navigate these quirks.
A strong specification means having a stable definition of the inline syntax.

Here's what we need:

* To define a formal grammar for the inline syntax that can be documented in the specification
* To be able to produce a full parse tree independent of output format to verify the behavior of an implementation
* To decouple parsing from conversion; parsing should not rely on conversion; the output should not affect parsing
* To be able to control where syntax rules are applied to avoid unintended interpretation of the text
* To support constrained and nested syntax in a reliable way

A formal grammar is the only reasonable and portable way to describe AsciiDoc's inline syntax in a specification.

=== Benefits

The importance of having a formal grammar that includes the inline syntax cannot be overstated.

. It becomes feasible to verify compliance of an implementation since parsing generates a complete parse tree and, in turn, an ASG, that includes inline nodes.
. It decouples the parsing of the language from the output format, which is essential to stay within the scope of this specification.
This decoupling also avoids idiosyncrasies introduced by parsing partially converted output or eagerly converting some elements.
In pre-spec AsciiDoc, it's common to have ordering or state problems that cause quirky behavior as a result of converting elements during parsing.
. Having a complete parse tree allows tooling to fully analyze the structure of a document and extract information from it, all the way down to the level of an inline node and its contents.
. A complete parse tree improves the accuracy of diagnostic messages, which include the precise source location, when things go wrong.

Some aspects of the syntax that were previously very difficult become much simpler.
For example, AsciiDoc can be enhanced to support lexical backslash escaping (i.e., backslash escaping of reserved characters and forms instead of contextual).
Syntax rules will naturally nest, avoiding ambiguity in how boundaries are interpreted or compelling the author to resort to hacks.
//In general, the syntax will be more consistent and well-behaved since markup can be interpreted or not based on where it resides in the flow.
With a formal grammar, the parsing becomes much more accurate, able to handle situations such as nested syntax and non-interpreted spans naturally, addressing many scenarios that were previously ambiguous.

=== Strategy

We've decided to describe the AsciiDoc syntax using PEG (parsing expression grammar).
Inline parsing using this formalism turned out to not be as difficult as we had initially thought.
Identifying and isolating the inline preprocessor made it even simpler, with only the side effect of extra effort to track offsets.
Most important, we determined that compatibility can be reasonably maintained.

The inline syntax in AsciiDoc lends itself well to a PEG grammar because it's naturally recursive, mostly due to limitations of the output formats (DocBook, HTML, etc).
We found that writers were naturally writing AsciiDoc in such a way that adhered to these limitations.
Thus, we can say with confidence that it's possible to accurately describe the inline syntax in AsciiDoc using PEG.
What's more, the inline syntax can be parsed efficiently from that grammar (with or without packrat parsing).

==== Remapping substitutions

One of the challenges with transitioning to a formal grammar was figuring out how to account for each of the substitution types in the grammar.
What we discovered is that not all the substitution types respect the inline structure.
Rather, they work outside of that structure, acting either as a preprocessor or postprocessor.
We identified the need to introduce an inline preprocessor and to rely on some postprocessing of the parsed structure as well.

Here's how the substitution types get mapped to the formal grammar:

* specialchars - a postprocessing operation on string nodes that is applied by the converter, thus not represented in the ASG
* attributes - handled by the inline preprocessor, which replaces each attribute reference with the value of the attribute to which it refers
* quotes - marked spans handled in the grammar using ordered choice rules
* replacements - typographic hints handled in the grammar using ordered choice rules
* macros
 ** inline passthroughs - protected spans handled by the inline preprocessor, which replaces passthroughs with placeholders during parsing; these placeholders are matched by a rule in the grammar, which restores the original text without parsing it further
 ** ordinary macros and shorthands - markup handled in the grammar using ordered choice rules
* post_replacements - markup handled in the grammar using ordered choice rules

Most of the substitutions map cleanly to the grammar as an ordered choice.
The obvious exceptions are specialchars, attributes, and inline passthroughs.
//The remainder of the inline syntax maps cleanly into rules of formal grammar arranged as an ordered choice.

==== Special characters

The specialchars ("`special characters`") substitution has always been a major anomaly of the AsciiDoc syntax.
The first problem is that it's biased towards the needs of an SGML output format like HTML.
While it encodes the correct characters for output formats in that family, it unnecessarily encodes those characters using the wrong syntax for other output formats such as groff.
So the definition of a special character is not universal.
More significantly, it alters the source so that substitutions have to account for these encoded characters in the grammar.

There's just no need to be doing the specialchars substitution at this stage.
These characters are not part of the inline syntax.
The converter should encode special characters characters in string nodes as required by the output format during conversion.

==== Inline preprocessor

With specialchars out of the way, the next group of syntax to address is that which influences the inline structure, but is not bound to it.
That syntax consists of attribute references (i.e., attributes) and inline passthroughs.

If we consider attribute references, the resolved value is the text the parser needs to operate on.
This resolved text could fundamentally change what the parser sees, potentially changing the structure.
For example, a URL macro may begin with an attribute reference.
The parser needs to see the URL added by the attribute reference, not the attribute reference itself.
This is a very similar situation to the preprocessor directives the line preprocessor handles.
So we have to look at attribute references as belonging to a preprocessing step.
The consequence is that this effectively reverses the order of the quotes and attributes substitutions so that quotes (marked spans) will be found and parsed in the value of an attribute when inserted into the text.

Inline passthroughs are the same.
But rather than substitute text, inline passthroughs mark regions of text that the inline parsing should skip over (i.e., non-interpreted spans).
These protected areas may also include attribute references that should be left uninterpreted.
Since the inline preprocessor leaves behind placeholders in the location of inline passthroughs, these placeholders must be matched by the inline grammar and the rule action must restore the protected text.

We can thus conclude that both attribute references and inline passthroughs are part of an inline preprocessor that operates on regular text before inline parsing begins.
The inline preprocessor needs to track offsets in the source when the text is changed so that the locations of inline nodes remains accurate.

== Related topics

While we've been able to model most aspects of the inline syntax as a formal grammar, there are still some topics that require more investigation.

Backslash escaping::
By switching to a formal grammar, we hope to be able make backslash escaping stable and reliable.
The current proposal is to use lexical backslash escaping, which will process the backslash in front of any symbol (including a backslash) or macro prefix.
However, there's a relationship to the use of backslashes to escape block-level syntax that still needs to be sorted out.

Boundaries of boxed attrlist on inline macros::
At the block level, a boxed attrlist always terminates at the end of a line.
In the inline syntax, the boxed attrlist on an inline macro can terminate anywhere in the line.
How that closing bracket is identified is still under question.
One approach is to match it eagerly, then process the attrlist (or content) inside the box.
This would avoid inline markup in an attrlist from masking the closing bracket.
However, it would require the use of more advancing parsing features (such as semantic predicates) to match the closing bracket unconditionally.
The other approach is to parse the attrlist as part of the macro rule.
However, this would allow behavior that deviates from how AsciiDoc works today.
This decision still needs to be resolved.

Subs on the pass macro::
The pass macro currently allows custom subs to be specified.
Since we're doing away with substitutions, we need to figure out how to map this intent to the structured parsing.
It may be that we're able to support common combinations of subs either by additional processing in the inline preprocessor and/or by inserting escapes into the input.
More research is still needed here to resolve how this is going to work.

== Backwards compatibility

While this decision brings a completely different mental model for how the text is interpreted, it does not mean abandoning compatibility.
Although the inline syntax is not currently defined using a formal grammar, that grammar has been inherent in the writer's perception of the inline structure.
We aim to distill that grammar so that regular text is interpreted in a way that matches that perception and, consequently, allows a processor to match the current output as closely as possible.
Where the behavior differs, it will likely differ in a way that more closely matches the writer's expectation, thus being a welcomed change.
In cases where the current behavior cannot be matched, the text should be interpreted in such a way that no information is lost.

Switching to a formal grammar does require doing away with the existing substitution order and interpretation of the inline markup in the convert phase.
This will affect two aspects of the language.
First, attribute references will be able to introduce text that contains marked spans (from the quotes substitution) which will now be interpreted.
The quotes substitution consists of formatted text like strong, emphasis, and monospace, as well as smart quotes.
Previously, it was necessary to force this substitution to happen where the attribute is defined using an inline pass macro.
This will no longer be necessary.
Second, the inline pass macro will not be able to arbitrarily change what parsing occurs.
However, we'll likely be able to support the most common scenarios to ensure compatibility (supporting limited permutations).
When that's not possible, we may rely on different parsing profiles.

By making this transition, we believe we will be able to achieve reasonable compatibility with existing documents while addressing severe limitations and idiosyncrasies that have long existed in the inline syntax of the AsciiDoc language.
