= SDR-7: Designate List Continuation as Universal Interrupting Line

[horizontal]
Related issues::
* https://gitlab.eclipse.org/eclipse/asciidoc-lang/asciidoc-lang/-/issues/42[asciidoc-lang#42]

== Context

A list continuation, by definition, is an interrupting line within a list to indicate that the ensuing block should be attached to the current list item.
It's interrupting nature is used as a way to imply correlation.
It reads as "`interrupt this block and attach the next block to the current list item to continue the sequence of attached blocks.`"

However, there's a question as to whether the list continuation should act as an interrupting line outside of a list as well, even though it doesn't otherwise have any meaning there.
This designation would make the list continuation universal, and thus context free.

== Accepted decision

The specification will state that a list continuation is a universal interrupting line, regardless of whether it occurs inside a list.
This decision was made both to simplify the rules for the author and to make writing an implementation easier.

== Decision summary

From a syntax perspective, there's no reason for a list continuation to act as an interrupting line outside of a list since it has no meaning in that scenario.
Consider the following case:

[,asciidoc]
----
one
+
two
----

The goal is to make the grammar rule for a paragraph, the most fundamental element in AsciiDoc, context free.
The decision to always treat the list continuation as an interrupting line helps to accomplish that goal.

If a list continuation only acts as an interrupting line within a list, then the grammar rule for a paragraph and attribute entry could not be context free.
In other words, the rule has to depend on where it's being evaluated, which is to say it must be contextual.

To account for this contextual behavior, the grammar rule either has to use a semantic predicate so it behaves differently inside of a list, or a dedicated hierarchy of grammar rules has to be used for blocks within a list to encode this behavior directly into the rules.
Either way, this makes it much harder for an implementation.

If the list continuation is classified as a universal interrupting line, it means the implementation doesn't need to track whether a block with implicit boundaries is inside a list or otherwise use a dedicated set of rules to be evaluated in this scenario.

With this universal rule in place, the previous example would produce two paragraphs, as represented by this HTML:

----
<p>one</p>
<p>+
two</p>
----

The list continuation interrupts the first paragraph, causing it to end.
However, since the list continuation is not consumed and otherwise interpreted outside of a list, it becomes the first line of the second paragraph.

Making the list continuation universal also means it may be possible for the priority line processor (i.e., the block preprocessor) to not have to keep track of when a line is inside a list or not, thus making that function more lightweight as well.
Thus, this designation is a small trade-off to lower the barrier for creating an implementation (which is already hard enough as it is).

== Backwards compatibility

If only by chance, both Asciidoctor and its predecessor already treat a list continuation as a universal interrupting line.
By making this decision, we're solidifying the implementation-defined behavior (and rationalizing why the list continuation is interrupting even when it doesn't serve its main purpose).
There's no impact on existing documents.

== Consequences

Encountering a list continuation outside of a list is very rare.
Given that there are implementation benefits and a guarantee of backward compatibility by making it universal, there are more benefits than consequences in doing so.
