= SDR-8: Designate List Item as Interrupting Line only for Principal Text

[horizontal]
Related issues::
* https://gitlab.eclipse.org/eclipse/asciidoc-lang/asciidoc-lang/-/issues/42[asciidoc-lang#42]

== Context

The principal text of a list item can be interrupted by a sibling or nested list item, which is well-established behavior in AsciiDoc.
This rule applies to list items in lists (unordered, ordered, etc) as well as description lists.
We need to decide whether a list item acts as an interrupting line for a block attached to a list item since this was never clearly stated in pre-spec AsciiDoc.
This pertains both to an attached paragraph and an attached attribute entry with a continuing value.

== Accepted decision

The specification will state that a sibling or nested list item acts as an interrupting line for the principal text, but does not act as an interrupting line for an attached block, such as a paragraph in a list.

This decision was made both to simplify the rules for the author and to make writing an implementation easier.

== Decision summary

A sibling or nested list item can interrupt the principal text of a list item.
It would be incredibly difficult to change this rule now as it's both commonplace in lightweight markup languages and most AsciiDoc documents rely on it.
(If we tried to change it, there would be riots).

The following AsciiDoc will produce an unordered list with three items:

[,asciidoc]
----
* first
* another
that wraps
* last
----

Aside from the fact that allowing this interruption has precedent and seems intuitive, there's a strong technical reason for why it can be allowed.
The list item principal is parsed along with the list item marker.
In other words, the principal text of a list item is part of the same form.
Thus, the grammar rule implicitly knows it's in a list and therefore can anticipate an approaching list item.
This syntax rule is naturally context free.

On the other hand, a paragraph attached to a list item is handled by the paragraph rule, which is used both inside and outside of a list.
As such, that rule doesn't implicitly know it's in a list item.

Consider the following AsciiDoc:

[,asciidoc]
----
* list item
+
supporting text
* not the next list item
----

In order to allow the list item to interrupt the attached paragraph, the paragraph rule would have to consider whether it's being evaluated inside of a list.
We would prefer the rule to be context free.
(The same motivation as discussed in SDR-7).
And since the list item cannot interrupt a paragraph outside of a list, it should not be able to interrupt one inside of a list either.

In order for the parser to find a list item that follows an attached paragraph, that paragraph has to have already been interrupted.
One way to do that is to insert an empty line above the sibling list item.

[,asciidoc]
----
* list item
+
supporting text

* next list item
----

For a nested list item, a block attribute line could be used as an interrupting line instead:

[,asciidoc]
----
* list item
+
supporting text
[upperalpha]
** nested list item
----

If there's no interrupting line between the attached paragraph and the next list item, then what appears to be a list item becomes a wrapped line of the attached paragraph.

== Backwards compatibility

Asciidoctor and its predecessor allow a list item to interrupt the principal text of the preceding list item.
Thus, we're merely solidifying the implementation-defined behavior.
There's no impact on existing documents.

Where we begin to deviate is whether a list item interrupts a paragraph attached to a list item.
It just so happens that Asciidoctor's predecessor does not allow this.
Thus, by making this decision, we're returning to the original implementation-defined behavior.
There are some documents out there that were written to these rules.
Additionally, all the examples in the Asciidoctor documentation happen to be written this way.
Its also the style that has been most advocated by the Asciidoctor project.

Technically, Asciidoctor does allow a sibling list item (but not a nested list item) to interrupt an attached paragraph.
However, a strong case can be made that this behavior is incorrect.
The reason has to do with how list parsing is implemented in Asciidoctor.
Asciidoctor finds all the lines up until the next sibling list item or end of list, then parses them.
In doing so, it introduces an artificial boundary for the current list item that does not properly account for all the nested grammar rules.
We can conclude from this that allowing a sibling list item to interrupt an attached paragraph is actually a side effect of the implementation and not actually the intended behavior.

== Rejected alternative

One alternative that was considered is to make a list item a universal interrupting line.
This idea is certainly alluring, most notably because Markdown supports it (though reStructuredText does not).
The problem is that it would be a strong deviation from a two decade-old AsciiDoc rule, would require re-education, and could break countless documents.

Consider one case where this would cause the parsing to go awry.

[,asciidoc]
----
The default limit for the number of concurrent operations is
1. This limit can be changed using the configuration file.
----

If a list item were an interrupting line, the wrapped line would become a list.
This is definitely not what the author expects to happen.
The author would now have to be very conscious of where wrapping occurs and consider whether the wrapped line is going to be treated as a list.
It gets even more complex (and hard to spot) when considering other list types such as a description list.

Another key reason against this alternative is that it makes the grammar rule for a paragraph much, much more complex and processor intensive.
Paragraphs are the most common element in an AsciiDoc document by far.
Having to check the start of every line of a paragraph for a list item means that the grammar rule for lists are evaluated for nearly every line in the document.

Yet another key reason against this alternative is that this opens up a Pandora's box for what can interrupt a paragraph.
Why couldn't a section title interrupt a paragraph then?
Would it be all lists or just some?
What about a block macro?
All these interrupting lines just make it tedious for the author to write a simple paragraph.

The final reason against this alternative is that we don't want to encourage writers to collapse empty lines between blocks.
Next they will want to write separate paragraphs with no empty lines between them.
When you make blocks in AsciiDoc, they should be separated by an empty line (or a list continuation when inside a list).
We want that style to be prevelant as it's a key part of what makes AsciiDoc look like AsciiDoc.
