= SDR-1: Add Variable-length Delimiter Form for Open Block

== Accepted decision

The specification will introduce a new structural container (i.e., a block form) for the open block that uses variable-length delimiters.
The delimiters will consist of four or more tilde characters on their own line (e.g., `+~~~~+`).

== Decision summary

By making this addition, the structural container for open blocks will be consistent with other reusable structural containers (four character minimum for delimiters) and support nesting (by varying the delimiter length).

The open block is the only block whose structural container has a uniform delimiter line with a restricted length (two characters instead of the standard four character minimum).
Not only does it look different, the two hyphen delimiter form (`--`) prevents the open block from being directly nested inside another open block because the delimiter length cannot be varied.

Nesting open blocks is useful for representing hierarchical elements not supported inherently in AsciiDoc (such as supporting custom layouts for landing pages without resorting to embedded HTML), enclosing the contents of a complex list item, or allowing an extension to define boundaries for a custom block without inferring other semantics.
In each of these scenarios, the use of the open block as a container should not restrict the use of open blocks within that container.
The open block is arguably the most versatile block, and yet its use is extremely limited because it cannot be nested.

It's not enough to permit the length of the `--` delimiter to be varied because a delimiter line of four or more hyphens `----` is already reserved for a listing block.
Thus, changing the delimiter character (from `-` to `~`) is necessary.
Four or more tildes (`+~~~~+`) was selected as the delimiter line because the tilde is typically present on keyboards and the characters sit in the middle of the line, making it easier to read as a delimiter line.

To view the complete discussion leading to this decision, including additional reasoning, requirement, questions, and discarded alternatives, see https://gitlab.eclipse.org/eclipse/asciidoc-lang/asciidoc-lang/-/issues/27[issue #27].

== Language change examples

Below is an example of an open block that's demarcated using the new variable-length delimiter form (`+~~~~+`).

[,asciidoc]
----
~~~~
This is an open block delimited using the new standard length delimiter line.
~~~~
----

In the next example, two open blocks are directly nested in a parent open block (using `+~~~~~~+` and `+~~~~+` delimiter lines, respectively).

[,asciidoc]
----
~~~~
Here are some boxes:

~~~~~~
Box A

This is a nested open block.
~~~~~~

~~~~~~
Box B

This is another nested open block.
~~~~~~
~~~~
----

== Backwards compatibility

The two hyphen delimiter form (`--`) will be marked as deprecated in the AsciiDoc language.
However, the grammar will still have to allow use of the legacy form for backwards compatibility.
