= Block Parsing and Structural Forms

== Block parsing

Block element parsing takes precedence over inline element parsing.
Each block should be parsed in the order it appears in the document.
How a block is identified and parsed is determined by a block's structural form in the source text and the content model that applies to the structural form.
Discrete headings are the one exception to this rule.

The parser identifies a block using its structural form in the source text.
The structural form controls how the parser determines the boundaries of a block.
The structural form also tells the parser the default content model to apply to the block.
If the content model of the block allows the block to contain child blocks, the parser will descend into the block to search for and identify any child blocks.
Once the parser has identified the boundaries of a block, the lines that comprise it, and, if allowed, the boundaries and lines of any child blocks, it will then determine if and how the lines in the block should be parsed.

If and how the lines that comprise a block should be parsed is determined by the block's content model and further refined by the block style or macro name of the block.
The block's content model and its style or macro name instruct the parser whether it should change the block from one type to another, run the inline preprocessor in a certain mode on the lines, and run the inline parser on the lines.
Inline parsing occurs as soon as the end of the block is identified.
The inline parsing of a block always happens before the inline parsing of blocks that follow the block in document order.

When the parser completes the parsing of a block it records the name of the block, its variant (if applicable), its structural form, and any block metadata as properties of a block node in the ASG.

== Block structural forms

In AsciiDoc, there are various structural forms, which are the building blocks of the language at the block level.
Each structural form indicates how the block is expressed in the source text.
These forms are recognized by the parser based on the grammar rule that they match.
The structural form also informs the parser what block content model it should apply to the lines that comprise the block.

Once the parser identifies what the structure is and the block content model associated with the structure, it follows certain rules for how to identify the lines that comprise the block, how to process any leading markers or surrounding delimiter lines, and whether to search for and parse any child blocks within the parent block.
The block parser should identify the block and its boundaries without considering any of the block metadata, including the block style attribute or the block macro name.
In other words, the block style attribute and block macro name should not influence how the parser identifies the block structure.
The one exception to this rule is the discrete block style on a heading.
In this case, the style is effectively acting as part of the structural form.
// TODO: we may consider introducing `#` as the marker for discrete headings so the parser does not have to rely on the style to identify the form; this will make creating parsers easier; `=` for section, `#` for discrete

The block structural forms are: paragraph, indented line, delimited block, block macro, shorthand block macro, heading, and list item.
The structural form is recorded by the `form` property on a block node in the ASG.

=== Paragraph form

The paragraph block form is composed of a sequence of contiguous, non-interrupting lines of source text.
The first line of the source text may not start with a space character (unless the paragraph is annotated with the `normal` style); it should start directly adjacent to the left margin.
Line breaks are not significant between adjacent lines in a paragraph.
Repeating spaces are not significant between characters in a paragraph.
(A conforming processor does not have to remove line breaks and repeating spaces if the output format normalizes them).
A paragraph block ends when the block parser encounters any of the following interrupting lines and syntax:

* empty line
* block attribute line
* block delimiter line
* list continuation line (proposed)
* table cell delimiter (when the paragraph occurs anywhere inside a table)

The default content model of the paragraph form is the basic content model.

////
=== Indented form

=== Delimited form

=== Macro form

=== Shorthand macro form

=== Heading (marked, prefixed?) form

=== List item form

=== dlist item form
////
