= Blocks

== Block elements

Block elements, referred to as blocks, are discrete, linewise chunks of source text that form the main structure of an AsciiDoc document.
Block elements are stacked vertically, one block below another in document order, in the source text.
A block always starts at the beginning or effective beginning of a whole line and ends on a whole line (except for table cells).

Block elements are separated from one another by boundaries.
These boundaries are either implicit, such as an empty line, or explicit, such as a delimiter line that is part of an enclosure.
An enclosure is a source feature of some blocks.
Specifically, a block element consists of two or three source features: an enclosure, content, and metadata.
These three features are described in the following sections.

=== Boundaries and enclosures

The boundaries of a block define the start and end of a block.
A block boundary is an interrupting line that begins or ends the parsing context of a block.
Some blocks have explicit boundaries that mark the start and end of a block's content.
These explicit boundaries are represented by a balanced, matching pair of delimiter lines in the source text, and they are referred to as an enclosure because they enclose the content of the block.

The boundaries of other blocks are implicit.
For example, the boundaries of a paragraph block are implicit because they can be represented by an empty line or by the boundary of a parent or sibling block, such as the delimiter line of a delimited block.

How the boundaries of a block are represented in the source text is defined by the structural form of a block.

=== Content

The content of a block is one or more lines of source text, which may consist of other blocks or inlines as permitted by the block's content model.
The block's content always starts at the beginning or effective beginning of a new line (except for table cells).
The content of a block may end on the same line it starts on or on a subsequent line.

What content a block can contain and how that content is handled is determined by the content model to which the block belongs.

=== Metadata

A block element can have metadata, such as a block title line, block attribute lines, or boxed attribute list.
