= Paragraph

// TODO: the syntax examples, grammar, and ASG schema and examples should be included into this document from external sources

== Description

Paragraphs are a foundational structure in AsciiDoc.
A *paragraph* is a block element comprised of a sequence of contiguous, non-interrupting lines that contain inline preprocessor directives, inline elements, and uninterpreted text.
If a line isn't recognized as another block element or structural form, it's interpreted as a paragraph.
Unrecognized syntax, or syntax not permitted inside a paragraph, is retained and categorized as uninterpreted text.

=== Syntax examples

.A paragraph with single line
[,asciidoc]
----
A paragraph that consists of a single line.
----

.A paragraph with multiple, wrapped lines
[,asciidoc]
----
This paragraph has multiple lines that wrap after reaching the 72
character limit.
----

.Sibling paragraphs
[,asciidoc]
----
This document has multiple paragraphs.

Paragraphs are separated by one or more empty lines.
----

.A paragraph with block metadata
[,asciidoc]
----
[#p1]
.The one and only
Paragraph with block title and attribute lines.
----

== Form, content model and context

[cols="2h,4"]
|===
|Element type |Block
|Structural form |Paragraph
|Content model |Basic
|Permitted content |Text, Inline elements, Inline preprocessor directives; may vary if style is specified
|Interrupting lines and syntax forms |Empty line, Block attribute line, Block delimiter line, List continuation line (proposed), Table cell delimiter (when the paragraph occurs anywhere inside a table)
|Permitted parents |Document (if document has no sections), Preamble, Compound block, List item, Table cell
|DOM interface |Paragraph
|===

////
[horizontal,labelwidth=33%]
Element type:: Block
Structural form:: Paragraph
Content model:: Basic
Permitted content:: Text, Inline elements, Inline preprocessor directives; may vary if style is specified
Interrupting lines and syntax forms:: Empty line, Block attribute line, Block delimiter line, List continuation line (proposed), Table cell delimiter (when the paragraph occurs anywhere inside a table)
Permitted parents:: Document (if document has no sections), Preamble, Compound block, List item, Table cell
DOM interface:: Paragraph
////

The source of a paragraph must not be empty.
It may parse to empty if it contains only inline preprocessor directives that all resolve to empty.

=== Attributes and metadata

A paragraph can accept the following attributes and metadata:

* Block title (defined as title line or named attribute)
* id (named and shorthand forms)
* reftext (named and shorthand forms)
* role(s) (named and shorthand forms)
//** lead (move to expected converter behavior)
* options (named and shorthand forms)
* style (positional form)
** attributes applicable to style
* data- named attributes

// The following paragraph is derived from SDR 003. We definitely shouldn't be re-describing how blocks are generally parsed in each block description, so I'm keeping this minimalistic because 1) it will be thoroughly explained in the high-level block section, and 2) we're still hardening the block parsing rules and refining the description, so we don't want to have to be contiuously updating all the different block sections because we were too verbose.
The block parser must parse a paragraph according to the rules of its structural form (Paragraph) and content model (Basic), regardless of the presence of an explicit style.
Only after the block parser completes parsing the block is the style evaluated.
If a style is specified on a paragraph, the paragraph may be transformed into another block type.
The style can impact how inlines are parsed and determine the block's name and variant (if applicable).

== Grammar

The grammar rule for a paragraph is defined as follows:

----
paragraph = &(!lf . eol / !any_block_delimiter_line) line|1.., !(list_continuation / any_block_delimiter_line / block_attribute_line)|
----

This rule is considered only after considering all other blocks.
This grammar rule does not take into account the behavior of the priority line processor (i.e., block preprocessor).
The rule also does not include the match for any block metadata that preceeds the paragraph.
Rather, the rule assumes any block metadata has already been consumed (and stored) and can be accessed from the rule's action (it's not necessary to reparse the block metadata before considering each block rule).
What the rule actually matches can be understood as follows:

----
paragraph_with_block_metadata = lf* @(block_metadata !heading paragraph)
----

The paragraph rule's action is expected to apply the consumed block metadata to the paragraph and run the complete inline parser after the rule is matched (assuming no style is specified).
Here's how the rule action may be defined:

[,js]
----
const location_ = getLocation()
const metadata = processBlockMetadata()
const node = {
  name: 'paragraph',
  type: 'block',
  inlines: parseInline(lines.join('\n'), {
    attributes: getDocumentAttributes(),
    locations: createLocationsForInlines(location_),
  }),
  location: toSourceLocation(location_),
}
return applyBlockMetadata(node, metadata)
----

== ASG schema and examples

The ASG schema for a paragraph is a specialization of a leaf block that extends an abstract block and is defined as follows:

.ASG schema
[,json]
----
"paragraph": {
  "type": "object",
  "allOf": [{ "$ref": "#/$defs/abstractBlock" }],
  "unevaluatedProperties": false,
  "required": ["name"],
  "defaults": { "inlines": [] },
  "properties": {
    "name": {
      "type": "string",
      "constant": "paragraph"
    },
    "form": {
      "type": "string",
      "enum": "paragraph"
    },
    "inlines": { "$ref": "#/$defs/inlines" }
  }
}
----

Here's an example of an ASG node for a paragraph that has multiple lines:

.ASG example
[,json]
----
{
  "name": "paragraph",
  "type": "block",
  "inlines": [
    {
      "name": "text",
      "type": "string",
      "value": "This paragraph has multiple lines that wrap after reaching the 72\ncharacter limit.",
      "location": [{ "line": 1, "col": 1 }, { "line": 2, "col": 16 }]
    }
  ],
  "location": [{ "line": 1, "col": 1 }, { "line": 2, "col": 16 }]
}
----

//== DOM
