// TODO insert xrefs to supporting sections once their available to reduce repitition
= Strong Span

== Description

Text marked as strong indicates that the content has greater importance or seriousness compared to the surrounding content.
A *strong span* is an inline element comprised of a sequence of characters that consists of uninterpreted text and inline markup, such as nested inline elements, resolved attribute references, inline passthrough placeholders, character references, etc.
When converted to HTML, this element will likely be represented using a `<strong>` tag.
Document viewers and browsers typically render a strong span using the bold weight from the same font family as the surrounding text.

// FIXME the description section is meant to be non-normative; we may need to move to Syntax > Rules
The strong span uses the asterisk (`+*+`) as the formatting mark.
Constrained text is marked as strong by enclosing it in a single pair of asterisks (`+*text*+`).
Unconstrained text is marked as strong by enclosing it in a pair of double asterisks (e.g., `+t**e**xt+`).

Unconstrained markup is matched without taking into account the surrounding characters.
The first match wins.

Whether constrained markup is matched depends on which characters are adjacent to the formatting marks.
The constrained rule must meet the following criteria:

* (assert) not wordy
* formatting mark (i.e., asterisk)
* (assert) not space
* one or more inline elements or uninterpretted characters
* (assert) not space
* formatting mark (i.e., asterisk)
* (assert) not wordy

The term "`wordy`" (aka AsciiDoc alnum) matches any alpha character defined by Unicode (`+\p{Alpha}+`) as well the numbers 0 to 9 (`0-9`).
This character group can be summarized using the regular expression `[\p{Alpha}0-9]`.
It does not match an underscore, unlike the `\p{Word}` Unicode property.

A span cannot overlap with another span (i.e., a span can only be a sibling or a child of another span).
The beginning and end of the span must fall within the boundaries of the parent inline.

=== Syntax examples

.A single word with constrained strong
[,asciidoc]
----
This coffee is *strong*.
----

.Multiple words with constrained strong
[,asciidoc]
----
This coffee is *very, very* strong.
----

.Unconstrained strong
[,asciidoc]
----
CRUD stands for **C**reate, **R**ead, **U**pdate, and **D**elete.
----

== Form, content model, and context

[cols="2h,4"]
|===
|Name |span
|Type |inline
|Variant |strong
|Structural form |constrained, unconstrained
|Content model |span
|Formatting mark |asterisk
|Permitted content |uninterpreted text, alternate strong span form, other inline elements, resolved attribute references, inline passthrough placeholders
|Disrupting markup |closing bracket of a parent macro (proposed)
|Permitted parents |inline element that supports inlines (such as another span), basic block, block title, interpolated block attribute value, list item principal text, basic table cell
|DOM interface |Span
|===

The unconstrained form takes precedence over the constrained form and is thus matched first.
At the time the constrained and unconstrained strong spans are parsed, the inline preprocessor will have already been run.
Only the value of attribute references will be visible at this time (and thus can influence parsing).
Inline passthroughs are represented using placeholders.
The passthrough content is restored after inline parsing is complete.

If the inline parser cannot match the grammar rules for a strong span within a sequence of characters, the parser treats the markup as uninterpreted text and no warning is issued.
For example, if the parser matches one asterisk (`*`), i.e., a potential opening strong mark, in a sequence of characters but eventually encounters the end of the text without matching a second (closing) strong mark, the asterisk in the character sequence has no special meaning an is passed through as uninterpreted text.

A strong span cannot be empty.
It may parse to empty (contain an empty array of inlines) if it contains only inline preprocessor directives that all resolve to empty.

=== Attributes and metadata

A strong span may have the following attributes:

* id (shorthand form)
* role(s) (shorthand form)

These attributes are defined using a limited boxed attrlist that precedes the formatting mark pair (e.g., `+[.application]*ACME*+`)
The limitation is that the attrlist may only contain attributes defined using the shorthand form.

== Grammar

The grammar rule for a strong span is defined as follows:

----
strong = unconstrained_strong / constrained_strong
----

The grammar rule for an unconstrained strong span is defined as follows:

// NOTE in an implementation, the unconstrained_strong rule may need to capture
// a preceding wordy* to ensure it sees an unconstrained form that follows a
// run of wordy and thus win out over a constrained form
----
unconstrained_strong = '**' (code / emphasis / !'**' constrained_strong / open / macro / unconstrained_strong_other)+ '**'
unconstrained_strong_other = wordy ('`' / '_' / '*' !'*' / '#') / not_mark_or_space+ (space not_mark_or_space+)* (space+ / &'**') / !'*' .
----

The grammar rule for a constrained strong span is defined as follows:

----
constrained_strong = '*' !space (code / emphasis / unconstrained_strong / open / macro / '*' !wordy / constrained_strong_other) (code / emphasis / unconstrained_strong / macro / constrained_strong_other)* '*' !wordy
constrained_strong_other = wordy* constrained_left_mark_in_strong / not_mark_or_space+ (space not_mark_or_space+)* &('*' !wordy) / space+ (!'*' / &'**' &unconstrained_strong / '*') / '*' &wordy / escaped / !(' ' / '*') .
----

NOTE: These rules do not yet account for the optional boxed attrlist that precedes the marked text.

These grammar rule do not take into account the behavior of the inline preprocessor.

The rules' actions are expected to tranform the match into an ASG node.
Here's how the rule action may be defined for the constrained strong span:

[,js]
----
return {
  name: 'span',
  type: 'inline',
  variant: 'strong',
  form: 'constrained',
  range: createRangeForSpan('constrained', range(), offset()),
  inlines,
}
----

The range is later translated into a location value by a postprocessor.

== ASG and DOM

The ASG schema for a paragraph is a specialization of an inline span that extends an abstract inline parent and is defined as follows:

[,json]
----
"inlineStrongSpan": {
  "type": "object",
  "allOf": [{ "$ref": "#/$defs/abstractParentInline" }],
  "unevaluatedProperties": false,
  "required": ["name", "variant", "form"],
  "properties": {
    "name": {
      "type": "string",
      "const": "span"
    },
    "variant": {
      "type": "string",
      "const": "strong",
    },
    "form": {
      "type": "string",
      "enum": ["constrained", "unconstrained"]
    }
  }
}
----

Here's an example of an ASG node for a constrained strong span that has multiple words:

[,json]
----
{
  "name": "span",
  "type": "inline",
  "variant": "strong",
  "form": "constrained",
  "inlines": [
    {
      "name": "text",
      "type": "string",
      "value": "very, very",
      "location": [{ "line": 1, "col": 17 }, { "line": 1, "col": 26 }]
    }
  ],
  "location": [{ "line": 1, "col": 16 }, { "line": 1, "col": 27 }]
}
----

//== DOM
