// tag::b-nonselect[]
----
line of code // <1>
line of code # <2>
line of code ;; <3>
line of code <!--4-->
----
<1> A callout behind a line comment for C-style languages.
<2> A callout behind a line comment for Ruby, Python, Perl, etc.
<3> A callout behind a line comment for Clojure.
<4> A callout behind a line comment for XML or SGML languages like HTML.
// end::b-nonselect[]

// tag::line-comment[]
[source,erlang,line-comment=%]
----
-module(hello_world).
-compile(export_all).

hello() ->
    io:format("hello world~n"). % <1>
----
<1> A callout behind a custom line comment prefix.
// end::line-comment[]

// tag::disable-line-comment[]
[source,asciidoc,line-comment=]
----
-- <1>
A paragraph in an open block.
--
----
<1> An open block delimiter.
// end::disable-line-comment[]

// tag::source-xml[]
[source,xml]
----
<section>
  <title>Section Title</title> <!--1-->
</section>
----
<1> The section title is required.
// end::source-xml[]

// tag::basic[]
[source,ruby]
----
require 'sinatra' <1>

get '/hi' do <2> <3>
  "Hello World!"
end
----
<1> Library import
<2> URL mapping
<3> Response block
// end::basic[]

// tag::auto[]
[,ruby]
----
require 'sinatra' <.>

get '/hi' do <.> <.>
  "Hello World!"
end
----
<.> Library import
<.> URL mapping
<.> Response block
// end::auto[]

// tag::auto-repeat[]
[,ruby]
----
require 'asciidoctor' <.>

puts Asciidoctor::VERSION <1>

Asciidoctor.convert_file 'README.adoc' <.>
----
<.> The require statement exports the class from the gem to the global scope.
<.> We can then call methods provided by that class.
// end::auto-repeat[]

// tag::b-src[]
[source,ruby]
----
require 'sinatra' // <1>

get '/hi' do // <2>
  "Hello World!" // <3>
end
----
<1> Library import
<2> URL mapping
<3> HTTP response body
// end::b-src[]

// tag::co-icon[]
= Document Title
:icons: font <1>

NOTE: Asciidoctor supports font-based admonition
icons, powered by Font Awesome! <2>
// end::co-icon[]
