= Project Governance

== Project Team

The project team is the collective of active committers with responsibilities and privileges on this project.

[#values]
== Values and Conduct

As part of being an Eclipse Foundation project, this project community is expected to follow and uphold the https://www.eclipse.org/org/documents/Community_Code_of_Conduct.php[Eclipse Community Code of Conduct].
We, as the project community, pledge to uphold this code to foster a professional, respectful, and welcoming environment.

Participants that use passive-aggressive, disrespectful, or dismissive language or tones, act unprofessionally, or otherwise violate the Code of Conduct will receive a warning from the Project Team informing them that their actions are not acceptable.
If a second incident occurs, the Project Team may ask the individual to voluntarily leave the community for a period of time and/or send a mailto:codeofconduct@eclipse.org[code of conduct report to the Eclipse Foundation].

Any community member can submit a code of conduct report to Eclipse.
An individual doesn't need to wait for the Project Team to take action.
Nor does that individual need to inform the Project Team that they are filing a code of conduct report.

[#decision-process]
== Decision process

Technical, editorial, and governance decisions are made using the following methods.

=== Silent consensus

Silent consensus is the default decision mechanism for this project.
When an issue is filed, a project team member will review it for completeness and assign labels to it.
Issues that have passed triage (`triage: passed` label) and merge requests (MRs) that aren't flagged for an assessment review, a request for changes, or a request for more information, can be accepted by silent consensus.
*Silent consensus cannot be reached until the issue or MR has been available for comment for at least 48 business hours.*
This allows everyone to have enough time to evaluate and respond to the issue or MR.
Additionally, MRs should be reviewed by at least one project team member.
A team member cannot review their own MR.
If no one <<objections,objects>> by the end of the silent consensus period, the issue or MR is accepted by the project.

=== Assessments

When an issue is flagged for an assessment review, a self-selecting group of community members will work with the issue submitter to evaluate the proposal and address any concerns about its completeness, scope, feasibility, impacts, etc.
Once the group reaches consensus on the proposal, the updated proposal is then subject to silent consensus.
In some cases, a draft MR may be submitted during an assessment review to refine possible solutions and discover obstacles.
The issue is accepted and a MR implementing the proposal can be submitted if no one objects during the consensus period.

[#objections]
=== Objections

Any objections to an issue or MR must include a clear reason for that objection, and, where possible, provide a set of actionable steps alongside the objection.
The objector must remain responsive for further discussion about the issue or MR until their concerns are resolved or they withdraw their objection.
If the objector isn't responsive for 7 days after they raised the objection or they're unable to clarify their objection if asked for further information by the project team, the project team can dismiss the objection.

=== Voting

If consensus can't be reached on an issue or MR that introduces significant breaking changes, but a decision one way or the other must be made, a team member may call for a vote.

A vote must be open for at least five days or until a majority of active project members have voted when further votes won't change the final decision.
The end date should be clearly stated in the call to vote.

Votes are performed electronically using a yes/no/abstain reply system, where +1 is yes, -1 is not, and 0 is abstain.
No other responses are recognized.

When a vote is called on an issue or MR, a majority of active project team members must vote in favor (yes) for a proposal to be approved.
