name: Spec coverage

on:
  push:
    branches: main

jobs:
  trigger:
    name: Trigger coverage run
    runs-on: ubuntu-latest

    steps:
      - name: Trigger coverage run in asciidoc-parser-coverage
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.COVERAGE_ACTIONS_TRIGGER }}
          repository: scouten/asciidoc-parser-coverage
          event-type: adoc-parser-updated
